"""
FHIR Export ORM Model (`fhir_exports` table)
============================================

File Purpose:
-------------
Stores generated ABDM-compliant Fast Healthcare Interoperability Resources (FHIR R4)
JSON payloads and tracking status for electronic health record exchange.

What it does:
-------------
1. Stores standardized FHIR Bundle JSON (Encounter, Patient, Condition, DocumentReference).
2. Maintains export status (PENDING, EXPORTED, FAILED, MOCKED).
3. Links directly to the intake session and patient.

Connected to:
-------------
- `backend/app/models/session.py`: Belongs to `SessionModel` (1:1).
- `backend/app/services/fhir_exporter.py`: Generated by FHIR conversion service.
- `backend/app/api/fhir.py`: Downloaded or queried via FHIR export endpoints.
"""

import uuid
from typing import Optional
from sqlalchemy import String, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .base import Base, TimestampMixin


class FHIRExportModel(Base, TimestampMixin):
    """
    SQLAlchemy model representing the 'fhir_exports' database table.
    """
    __tablename__ = "fhir_exports"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id: Mapped[str] = mapped_column(String(36), ForeignKey("sessions.id", ondelete="CASCADE"), unique=True, index=True)
    fhir_resource_type: Mapped[str] = mapped_column(String(32), default="Bundle")
    fhir_json_payload: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(32), default="MOCKED")  # MOCKED, EXPORTED, FAILED
    abdm_care_context_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Relationships
    session: Mapped["SessionModel"] = relationship("SessionModel", back_populates="fhir_export")
