"""
Summarizer Service Data Schemas
===============================

File Purpose:
-------------
Defines the Pydantic data schemas for incoming clinical summary requests (combining
patient demographics, dialogue Q&A history, and OCR extracted document entities)
and outgoing structured clinical case note drafts.

What it does:
-------------
1. Validates the composite input payload needed for LLM case summary generation.
2. Standardizes clinical note sections (Chief Complaint, History of Presenting Illness,
   Past Medical History, Current Medications, Allergies, Relevant Lab Findings, AYUSH Dosha/Prakriti).
3. Enforces the mandatory programmatic disclaimer: "AI-drafted. Physician review required before use."

Connected to:
-------------
- `ai-services/summarizer/app/prompts/clinical_prompts.py`: Uses these fields to populate prompt templates.
- `ai-services/summarizer/app/services/summary_service.py`: Serializes and deserializes LLM responses.
- `ai-services/summarizer/app/main.py`: Used in endpoint route definition.
- `backend/app/clients/summarizer_client.py`: Consumed by the Main Backend.
- `backend/app/models/summary.py`: Maps directly to PostgreSQL `case_summaries` table.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class PatientContext(BaseModel):
    """Demographic and contextual metadata for the patient."""
    name: str = Field(..., description="Patient full name")
    age: int = Field(..., description="Patient age in years")
    gender: str = Field(..., description="MALE, FEMALE, or OTHER")
    preferred_language: str = Field(default="en", description="Patient interview language")


class DialogueAnswer(BaseModel):
    """Q&A item captured during the patient interview."""
    question_key: str = Field(..., description="Question topic key")
    question_text: str = Field(..., description="Prompt asked to the patient")
    answer_text: str = Field(..., description="Patient's response")


class OCREntity(BaseModel):
    """Clinical entity extracted from scanned prescriptions or lab reports."""
    entity_type: str = Field(..., description="MEDICINE, LAB_VALUE, DATE, DIAGNOSIS")
    entity_value: str = Field(..., description="Entity textual value")
    is_abnormal: bool = Field(default=False, description="Flag for abnormal lab findings")


class SummaryGenerationRequest(BaseModel):
    """
    Complete intake payload sent from Main Backend to Summarizer AI.
    """
    session_id: str = Field(..., description="UUID of the intake session")
    mode: str = Field(default="ALLOPATHIC", description="ALLOPATHIC or AYUSH")
    patient: PatientContext = Field(..., description="Patient demographic context")
    responses: List[DialogueAnswer] = Field(default_factory=list, description="Patient interview Q&A history")
    extracted_entities: List[OCREntity] = Field(default_factory=list, description="Entities parsed from documents")


class StructuredClinicalSummary(BaseModel):
    """
    Structured clinical case-note draft generated by LLM prompt engineering.
    Carries mandatory AI safety disclaimers and human-in-the-loop review flags.
    """
    session_id: str = Field(..., description="UUID of the associated session")
    chief_complaint: str = Field(..., description="Concise primary complaint summary")
    hpi: str = Field(..., description="History of Presenting Illness structured narrative")
    past_history: str = Field(default="None reported", description="Past medical and surgical history")
    current_medications: List[str] = Field(default_factory=list, description="Active medications synthesized from OCR and interview")
    allergies: List[str] = Field(default_factory=list, description="Known drug and environmental allergies")
    abnormal_findings: List[str] = Field(default_factory=list, description="Flagged lab abnormalities or high-risk indicators")
    ayush_observations: Optional[str] = Field(default=None, description="Ayurvedic/AYUSH clinical observations if mode was AYUSH")
    raw_ai_draft: str = Field(..., description="Complete drafted clinical text note")
    disclaimer: str = Field(
        default="AI-drafted. Physician review required before use.",
        description="Mandatory legal/safety disclaimer"
    )
    reviewed: bool = Field(default=False, description="Human review status; false until physician confirmation")
